name: Tests

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build packages
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Test packages
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
